# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-22 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200819_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_four_checkbox',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_one_checkbox',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_three_checkbox',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_two_checkbox',
            field=models.BooleanField(),
        ),
    ]
