# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-22 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200822_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='option_four_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_one_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_three_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_two_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
