# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-29 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200822_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('id',)},
        ),
    ]
