# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-24 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200823_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='images/None/no-img.jpg', upload_to='images', width_field=200)),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('link', models.URLField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/None/no-img.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default='', max_length=30),
        ),
    ]
