# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-24 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200824_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, default='images/None/no-img.jpg', upload_to='images'),
        ),
    ]
