# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-25 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200824_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advert',
            new_name='Advertisement',
        ),
    ]
