# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-25 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200825_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='link',
        ),
    ]
