# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-25 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_advertisement_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='link',
            field=models.URLField(default='', max_length=250),
        ),
    ]
