# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-25 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200825_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/None/no-img.jpg', upload_to='images')),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('link', models.URLField(default='', max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
