# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-25 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200825_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, default='images/None/no-img.jpg', upload_to='images'),
        ),
    ]
