# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-29 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='small_image',
            field=models.ImageField(blank=True, default='images/None/no-img.jpg', upload_to='images'),
        ),
    ]
