# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-27 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200827_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
