# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-12 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200827_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
