# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='short_description',
            new_name='facts',
        ),
    ]
