# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200813_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='facts',
        ),
        migrations.AddField(
            model_name='course',
            name='academic_sessions',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='certification_prior',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='confined_water',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='maximum_depth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='minimum_age',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='openwater_dives',
            field=models.CharField(default='', max_length=100),
        ),
    ]
