# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200819_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='online_offer_price',
        ),
    ]
