# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-03 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dive_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(max_length=500),
        ),
    ]
