# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-03 19:41
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dive_blog', '0002_auto_20200903_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
