# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-03 20:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dive_blog', '0003_auto_20200903_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
